# Generated by Django 2.0.7 on 2018-08-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
