# Generated by Django 2.0.7 on 2018-08-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
