# Generated by Django 2.0.7 on 2018-08-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_profile_plan_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(null=True)),
                ('JT_G01_COSPHI', models.TextField(null=True)),
                ('JT_G01_DAYAVA', models.TextField(null=True)),
                ('JT_G01_FREQ', models.TextField(null=True)),
                ('JT_G01_MONTHAVA', models.TextField(null=True)),
                ('JT_G01_NOMP', models.TextField(null=True)),
                ('JT_G01_NROTOR', models.TextField(null=True)),
                ('JT_G01_VANE', models.TextField(null=True)),
                ('JT_G01_VWIND', models.TextField(null=True)),
                ('JT_G01_GOPOS', models.TextField(null=True)),
                ('JT_G01_Ambient_Temp', models.TextField(null=True)),
                ('JT_G01_FrontBearing_Temp', models.TextField(null=True)),
                ('JT_G01_NacelleAmbient_Temp', models.TextField(null=True)),
                ('JT_G01_NacelleCB_Temp', models.TextField(null=True)),
                ('JT_G01_Nacelle_Temp', models.TextField(null=True)),
                ('JT_G01_RearBearing_Temp', models.TextField(null=True)),
                ('JT_G01_Rotor_Temp', models.TextField(null=True)),
                ('JT_G01_Stator_Temp', models.TextField(null=True)),
                ('JT_G01_Tower_Temp', models.TextField(null=True)),
                ('JT_G01_Transformer_Temp', models.TextField(null=True)),
                ('JT_G01_I_L1', models.TextField(null=True)),
                ('JT_G01_I_L2', models.TextField(null=True)),
                ('JT_G01_I_L3', models.TextField(null=True)),
                ('JT_G01_P', models.TextField(null=True)),
                ('JT_G01_U_L1', models.TextField(null=True)),
                ('JT_G01_U_L2', models.TextField(null=True)),
                ('JT_G01_U_L3', models.TextField(null=True)),
            ],
            options={
                'db_table': 'data',
            },
        ),
    ]
