# Generated by Django 2.0.7 on 2018-08-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20180812_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dashboard',
            field=models.TextField(db_index=True, default='', null=True),
        ),
    ]
