# Generated by Django 2.0.7 on 2018-08-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0015_auto_20180815_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(upload_to='media/%Y/%m/%d')),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
