# Generated by Django 2.0.7 on 2018-08-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_field',
            field=models.FileField(upload_to='%Y%m%d'),
        ),
    ]
