# Generated by Django 2.0.7 on 2018-08-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_auto_20180819_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='date_time',
            new_name='Date_time',
        ),
    ]
