# Generated by Django 2.0.7 on 2018-08-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0018_auto_20180820_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='JT_G01_Ambient_Temp',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_COSPHI',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_DAYAVA',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_FREQ',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_FrontBearing_Temp',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_GOPOS',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_I_L1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_I_L2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_I_L3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_MONTHAVA',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_NOMP',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_NROTOR',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_NacelleAmbient_Temp',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_NacelleCB_Temp',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_Nacelle_Temp',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_P',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_RearBearing_Temp',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_Rotor_Temp',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_Stator_Temp',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_Tower_Temp',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_Transformer_Temp',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_U_L1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_U_L2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_U_L3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_VANE',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='JT_G01_VWIND',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
