# Generated by Django 2.0.7 on 2018-08-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0019_auto_20180820_2244'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table=None,
        ),
    ]
