# Generated by Django 2.0.7 on 2018-08-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0020_auto_20180825_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Date_time',
            new_name='date_time',
        ),
    ]
