# Generated by Django 2.0.7 on 2018-08-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0021_auto_20180825_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_COSPHI',
            new_name='jt_g01_cosphi',
        ),
    ]
