# Generated by Django 2.0.7 on 2018-08-28 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0022_auto_20180828_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='jt_g01_cosphi',
            new_name='JT_G01_COSPHI',
        ),
    ]
