# Generated by Django 2.0.7 on 2018-08-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0023_auto_20180828_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_COSPHI',
            new_name='jt_g01_cosphi',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_DAYAVA',
            new_name='jt_g01_dayava',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_FREQ',
            new_name='jt_g01_freq',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_MONTHAVA',
            new_name='jt_g01_monthava',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_NOMP',
            new_name='jt_g01_nomp',
        ),
    ]
