# Generated by Django 2.0.7 on 2018-08-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0024_auto_20180828_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_I_L1',
            new_name='jt_g01_i_l1',
        ),
    ]
