# Generated by Django 2.0.7 on 2018-09-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0026_auto_20180911_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dashboard',
            field=models.TextField(db_index=True, default=''),
        ),
    ]
