# Generated by Django 2.0.7 on 2018-09-11 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0031_auto_20180911_0844'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile1',
        ),
    ]
