# Generated by Django 2.0.7 on 2018-09-11 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0032_auto_20180911_0902'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
