# Generated by Django 2.0.7 on 2018-09-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0033_auto_20180911_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_Ambient_Temp',
            new_name='jt_g01_ambient_temp',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_FrontBearing_Temp',
            new_name='jt_g01_frontbearing_temp',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_GOPOS',
            new_name='jt_g01_gopos',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_I_L2',
            new_name='jt_g01_i_l2',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_I_L3',
            new_name='jt_g01_i_l3',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_NROTOR',
            new_name='jt_g01_nrotor',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_NacelleAmbient_Temp',
            new_name='jt_g01_nacelleambient_temp',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_NacelleCB_Temp',
            new_name='jt_g01_nacellecb_temp',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_P',
            new_name='jt_g01_p',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_RearBearing_Temp',
            new_name='jt_g01_rearbearing_temp',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_Rotor_Temp',
            new_name='jt_g01_rotor_temp',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_Stator_Temp',
            new_name='jt_g01_stator_temp',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_Tower_Temp',
            new_name='jt_g01_tower_temp',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_Transformer_Temp',
            new_name='jt_g01_transformer_temp',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_U_L1',
            new_name='jt_g01_u_l1',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_U_L2',
            new_name='jt_g01_u_l2',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_U_L3',
            new_name='jt_g01_u_l3',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_VANE',
            new_name='jt_g01_vane',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_VWIND',
            new_name='jt_g01_vwind',
        ),
    ]
