# Generated by Django 2.0.7 on 2018-09-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0034_auto_20180916_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='JT_G01_Nacelle_Temp',
            new_name='jt_g01_nacelle_temp',
        ),
    ]
