# Generated by Django 2.0.7 on 2018-09-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0035_auto_20180916_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='width',
            field=models.IntegerField(default=1),
        ),
    ]
