# Generated by Django 2.0.7 on 2018-09-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0036_auto_20180918_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hight',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='width',
            field=models.IntegerField(default=2),
        ),
    ]
