# Generated by Django 2.0.7 on 2018-11-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0038_mli_g01'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mli_g01',
            old_name='date_time',
            new_name='Date_Time',
        ),
    ]
