# Generated by Django 2.0.7 on 2019-07-14 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0039_auto_20181126_0336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MLI_G01',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
