# Generated by Django 2.0.7 on 2019-07-18 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainsite', '0046_plan_table_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='file_path',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='last_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='file',
            name='permission_name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='plan_id',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Plan'),
        ),
        migrations.AddField(
            model_name='file',
            name='user_id',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_field',
            field=models.FileField(null=True, upload_to='%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hight',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='width',
            field=models.IntegerField(default=6),
        ),
    ]
