# Generated by Django 2.0.7 on 2019-07-18 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0047_auto_20190718_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='plan_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainsite.Plan'),
        ),
        migrations.AlterField(
            model_name='file',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
