# Generated by Django 2.0.7 on 2019-07-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0048_auto_20190718_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
