# Generated by Django 2.0.7 on 2019-07-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0049_file_file_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_field',
        ),
    ]
