# Generated by Django 2.0.7 on 2019-10-10 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainsite', '0050_remove_file_file_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MATLAB_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, null=True)),
                ('port', models.CharField(max_length=256, null=True)),
                ('deployable_archive', models.CharField(max_length=256, null=True)),
                ('parameters', models.CharField(max_length=256, null=True)),
                ('function_name', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_time', models.DateTimeField(auto_now=True)),
                ('permission_name', models.CharField(max_length=512, null=True)),
                ('program_description', models.TextField(blank=True, null=True)),
                ('plan_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainsite.Plan')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matlab_info',
            },
        ),
    ]
