# Generated by Django 2.0.7 on 2019-10-10 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0052_matlab_info_is_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matlab_info',
            table='matlab',
        ),
    ]
