# Generated by Django 2.0.7 on 2019-10-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0053_auto_20191010_1342'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matlab_info',
            table='matlab_info',
        ),
    ]
