# Generated by Django 2.0.7 on 2019-10-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0054_auto_20191010_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='doc_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='doc_path',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
