# Generated by Django 2.0.7 on 2019-10-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0055_auto_20191026_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='outputfile1',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='outputfile2',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
