# Generated by Django 2.0.7 on 2019-10-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0056_auto_20191026_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='outputfile2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
