# Generated by Django 2.0.7 on 2019-11-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0058_paper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
