# Generated by Django 2.0.7 on 2019-11-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0060_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='chinese_keyword',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='english_keyword',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='english_title',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
