# Generated by Django 2.0.7 on 2019-11-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0061_auto_20191107_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='chinese_title',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='link',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_year',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
