# Generated by Django 2.0.7 on 2019-11-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0062_auto_20191107_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paper',
            new_name='Papers',
        ),
        migrations.AlterModelTable(
            name='papers',
            table='papers',
        ),
    ]
