# Generated by Django 2.0.7 on 2019-11-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0063_auto_20191107_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
