# Generated by Django 2.0.7 on 2019-11-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0065_devices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Devices',
        ),
    ]
