# Generated by Django 2.0.7 on 2019-11-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0070_profile_plan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='plan_tmp_id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan_id',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
