# Generated by Django 2.0.7 on 2019-11-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0072_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_table',
            name='permission_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
