# Generated by Django 2.0.7 on 2019-11-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0073_auto_20191116_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_table',
            name='alias_table_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
