# Generated by Django 2.0.7 on 2019-11-16 14:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0074_plan_table_alias_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_table',
            name='columns',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
    ]
