# Generated by Django 2.0.7 on 2019-11-16 14:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0075_plan_table_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dashboard',
            field=django.contrib.postgres.fields.jsonb.JSONField(db_index=True, default='[{}]'),
        ),
    ]
