# Generated by Django 2.0.7 on 2019-11-16 14:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0077_auto_20191116_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_table',
            name='columns',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[{}]),
        ),
    ]
