# Generated by Django 2.0.7 on 2019-11-19 21:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0078_auto_20191116_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_table',
            name='columns',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[{}]),
        ),
    ]
